# Generated by Django 5.2.2 on 2025-07-31 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_available_product_combo_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comboorder",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="comboorder",
            name="total",
        ),
        migrations.AddField(
            model_name="comboorder",
            name="combo_type",
            field=models.CharField(default="0.00", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comboorder",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comboorder",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
