# Generated by Django 5.2.4 on 2025-07-31 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_comboorder_is_paid_remove_comboorder_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comboorder",
            name="combo_type",
            field=models.CharField(default="Essence", max_length=20),
        ),
        migrations.AlterField(
            model_name="comboorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
