# Generated by Django 5.2.4 on 2025-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_comboorder_combo_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="duration",
            field=models.CharField(default="0.00", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
            preserve_default=False,
        ),
    ]
