# Generated by Django 5.2.4 on 2025-07-31 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_orderitem_duration_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="service_name",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.service",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="duration",
            field=models.CharField(default="0.00", max_length=50),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
