# Generated by Django 5.2.2 on 2025-08-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_orderitem_service_name_orderitem_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comboorder",
            name="bank_receipt",
            field=models.ImageField(blank=True, upload_to="receipts/"),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("KHALTI", "Khalti"),
                    ("BANK_NIC", "NIC Asia Bank Transfer"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="payment_verified",
            field=models.BooleanField(default=False),
        ),
    ]
