# Generated by Django 5.2.2 on 2025-08-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_comboorder_bank_receipt_comboorder_is_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comboorder",
            name="payment_verified",
        ),
        migrations.AddField(
            model_name="comboorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
