# Generated by Django 5.2.2 on 2025-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_comboorder_payment_method_bankpayment_cart_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="service",
        ),
        migrations.AddField(
            model_name="comboorder",
            name="actual_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("PREPARING", "Preparing Your Items"),
                    ("DISPATCHED", "Dispatched for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="estimated_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
