# Generated by Django 5.2.2 on 2025-08-06 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_cartitem_cart_remove_cartitem_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comboorder",
            name="delivery_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="delivery_contact_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="comboorder",
            name="special_delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.comboorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("delivery_address", models.TextField(blank=True)),
                ("alternate_phone", models.CharField(blank=True, max_length=15)),
                (
                    "preferred_contact_time",
                    models.CharField(
                        choices=[
                            ("ANYTIME", "Anytime"),
                            ("MORNING", "Morning (9AM-12PM)"),
                            ("AFTERNOON", "Afternoon (12PM-5PM)"),
                            ("EVENING", "Evening (5PM-9PM)"),
                        ],
                        default="ANYTIME",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
