# Generated by Django 5.2.5 on 2025-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_trackingupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
